pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('DOCKERHUB_CREDENTIALS') // Змінна для облікових даних Docker Hub
        DOCKER_IMAGE_NAME = "andrew43/order_queue_app" // Ваше ім'я користувача
    }

    stages {
        stage('Checkout') {
            steps {
                // Клонуємо репозиторій
                git 'https://github.com/AndrewDem0/ProgramingTechnology-personal.git'
            }
        }

        stage('Build and Test') {
            steps {
                // Переміщуємося в директорію, де знаходяться всі потрібні файли
                dir('lab4_jenkins') { // Вкажіть назву папки, де ваш Dockerfile і Jenkinsfile
                    // Встановлюємо залежності (якщо є requirements.txt)
                    sh 'pip install -r requirements.txt || true'
                    
                    // Запускаємо тести
                    sh 'python3 -m unittest discover -s .'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                // Створюємо Docker образ
                script {
                    dir('lab4_jenkins') { // Повертаємося в директорію з Dockerfile
                        docker.build("${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    dir('lab4_jenkins') { // Повертаємося в директорію з Dockerfile
                        docker.withRegistry('https://registry.hub.docker.com', 'DOCKERHUB_CREDENTIALS') {
                            docker.image("${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}").push()
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Build, Test, and Docker Push were successful!"
        }
        failure {
            echo "Build, Test, or Docker Push failed."
        }
    }
}
