pipeline {
    options { timestamps() }  // Add timestamps to the logs
    agent none
    tools {
        dockerTool 'docker'  // Use Docker, configured in Jenkins Tools
    }

    stages {
        stage('Check scm') {
            agent any
            steps {
                checkout scm  // Checkout the code from SCM
            }
        }

        stage('Build') {
            steps {
                echo "Building ...${BUILD_NUMBER}"  // Build number
                echo "Build completed"  // Build completion confirmation
            }
        }

        stage('Test') {
            agent { 
                docker { 
                    image 'python:3.12-alpine'  // Use Python 3.12 container
                    args '-u root -w /workspace/Lab_4_2'  // Unix-style working directory path
                } 
            }

            steps {
                // Install pip and dependencies
                sh 'apk add --no-cache py3-pip'
                sh 'pip install xmlrunner'

                // Run the tests
                sh 'python3 -m unittest discover -s . -p "*_test.py"'
            }

            post {
                always {
                    // Archive the test results in JUnit format
                    junit 'lab4_jenkins/test-results.xml'
                }

                success {
                    echo "Application testing successfully completed"  // If tests pass
                }

                failure {
                    echo "Oooppss!!! Tests failed!"  // If tests fail
                }
            }
        }
    }
}
