pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('DOCKERHUB_CREDENTIALS') // Змінна для облікових даних Docker Hub
        DOCKER_IMAGE_NAME = "andrew43/order_queue_app" // Ваше ім'я користувача
    }

    stages {
        stage('Checkout') {
            steps {
                // Використовуємо автоматичну перевірку SCM
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                // Переміщуємося в директорію, де знаходяться всі потрібні файли
                dir('lab4_jenkins') { 
                    // Встановлюємо залежності
                    bat 'pip install -r requirements.txt || exit 0'
                    
                    // Запускаємо тести
                    bat 'python -m unittest discover -s .'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('lab4_jenkins') { 
                        // Створюємо Docker образ
                        docker.build("${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    dir('lab4_jenkins') { 
                        // Публікуємо Docker образ
                        docker.withRegistry('https://registry.hub.docker.com', 'DOCKERHUB_CREDENTIALS') {
                            docker.image("${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}").push()
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Build, Test, and Docker Push were successful!"
        }
        failure {
            echo "Build, Test, or Docker Push failed."
        }
    }
}
